#ifndef VOLUME_DESC_H
#define VOLUME_DESC_H

#define SGI_VIEW_BIAS				4.0f
#define SGI_NORMAL_BIAS				1.0f
#define SGI_CHANGE_THRESHOLD		0.5f
#define SGI_BRIGHTNESS_THRESHOLD	2.0f
#define SGI_NUM_RAYS_PER_PROBE		288
#define SGI_NUM_IRRADIANCE_TEXELS	6
#define SGI_NUM_DISTANCE_TEXELS		14
#define SGI_GRID_COUNT_X			20
#define SGI_GRID_COUNT_Y			12
#define SGI_GRID_COUNT_Z			16
#define SGI_GRID_SPACING_X			3.0f
#define SGI_GRID_SPACING_Y			3.0f
#define SGI_GRID_SPACING_Z			3.0f

#endif // VOLUME_DESC_H
//	EOF
