#ifndef VOLUME_DESC_H
#define VOLUME_DESC_H

#define SGI_VIEW_BIAS				0.1f
#define SGI_NORMAL_BIAS				0.02f
#define SGI_IRRADIANCE_THRESHOLD	0.25f
#define SGI_BRIGHTNESS_THRESHOLD	1.0f
#define SGI_NUM_RAYS_PER_PROBE		288
#define SGI_NUM_IRRADIANCE_TEXELS	6
#define SGI_NUM_DISTANCE_TEXELS		14
#define SGI_GRID_COUNT_X			20
#define SGI_GRID_COUNT_Y			16
#define SGI_GRID_COUNT_Z			20
#define SGI_GRID_SPACING_X			2.0f
#define SGI_GRID_SPACING_Y			2.0f
#define SGI_GRID_SPACING_Z			2.0f
#define SGI_MAX_RAY_DISTANCE		20.0f
#define SGI_HYSTERESIS				0.97f

#endif // VOLUME_DESC_H
//	EOF
